version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-test
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    command: ["sh","-c","chmod +x start-app.sh && ./start-app.sh"]

  db:
    image: mysql:8.0
    container_name: app-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: bank_transaction
      MYSQL_USER: transactions
      MYSQL_PASSWORD: transactions@2024
      MYSQL_ROOT_PASSWORD: transactions@2024up

#  redis:
#    image: redis:latest
#    container_name: lumen-redis
#    restart: unless-stopped
#    ports:
#      - "6379:6379"
